spring:
  cloud:
    nacos:
      # 注册中心
      discovery:
        server-addr: http://127.0.0.1:8848
        namespace: coin-dev
  session:
    timeout: 60
    store-type: redis
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    password: 65Yxd4PMYbTNAYHT
    url: jdbc:p6spy:mysql://194.41.36.123:3306/zhengtuo?characterEncoding=utf-8&useSSL=false
    username: zhengtuo

  jpa:
    generate-ddl: false
    show-sql: true

  data:
    mongodb:
      uri: mongodb://194.41.36.123:27017/bitrade

  ## redis\u670D\u52A1\u5668\u914D\u7F6E
  redis:
    database: 0
    host: 194.41.36.123
    password: Wrhwiydk6Z2
    port: 6379
    timeout: 30000

  #kafka
  kafka:
    bootstrap-servers: 194.41.36.123:9092
    producer:
      batch:
        size: 256 # \u6BCF\u6B21\u6279\u5904\u7406\u7684\u5927\u5C0F
      buffer:
        memory: 1048576 # \u7F13\u5B58\u6570\u636E\u7684\u5185\u5B58\u5927\u5C0F
      linger: 1 #linger\u6307\u5B9A\u7684\u65F6\u95F4\u7B49\u5F85\u66F4\u591A\u7684records\u51FA\u73B0
      retries: 0 # \u91CD\u4F20\u6B21\u6570
    consumer:
      auto:
        commit:
          interval: 100
        offset:
          reset: earliest
      concurrency: 9
      enable:
        auto:
          commit: false
      group:
        id: default-group
      maxPollRecordsConfig: 50
      session:
        timeout: 15000

decorator:
  datasource:
    p6spy:
      log-file: spy.log
      log-format: executionTime:%(executionTime) | sql:%(sqlSingleLine)
      logging: file

